on:
  push:
    branches:
      - main
name: Deploy website on push
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      VITE_BACKEND_SERVER: ${{ secrets.VITE_BACKEND_SERVER }}
      VITE_URL: ${{ secrets.VITE_URL }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies and build React app
        run: |
          cd client
          npm install
          npm run build -- --mode prod
      - name: Push client files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: "client/dist/"
          server-dir: "public_html/"
